### ISSUE TITLE
The Economist not working?

### ISSUE THREAD

**Issue by pimmelpiet** [iamadamdev/bypass-paywalls-chrome#474]
Hello, first of all great job with this little gadget. I used to use it for even more sites, but by now i have subscribed to Wired and some others. However, the economist with its 85$ 3 month plan is clearly out of my league although i use it a lot for university. They changed their site up for the new year, since then it's not working anymore. Maybe, only if you have a minute at some point, give it a glance! Again, great work :-)

**Comment by iscreamcoke** [comment]
This issue has been fixed by Magnolia, you can download his release here https://github.com/magnolia1234/bypass-paywalls-chrome/releases

**Comment by dtws1868** [comment]
> This issue has been fixed by Magnolia, you can download his release here https://github.com/magnolia1234/bypass-paywalls-chrome/releases

Hello, I have downloaded this release yet The Economist still does not work for me. Keeps refreshing to no success unfortunately.

**Comment by magnolia1234** [comment]
For Economist-fix use my master-zip. I'll add a v1.6.1b 'release' though.

**Comment by bwanaaa** [comment]
still not working as of 1/11/2020 3PM EST

**Comment by andyncake** [comment]
Still not working with 1.6.1a.

**Comment by magnolia1234** [comment]
Fix for Economist in v1.6.1b or master.

**Comment by IBNU1** [comment]
Where do you get v1.6.1b?

**Comment by magnolia1234** [comment]
https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by IBNU1** [comment]
It stopped working again even with the new one

**Comment by mlfood** [comment]
Same is happening for me today. Keeps refreshing and blocked.

**Comment by iamadamdev** [comment]
Please do not advertise your own repo in my repo otherwise I will be forced to ban you. You didn't even credit me in your repo either.

**Comment by iamadamdev** [comment]
Fixed.
