### ISSUE TITLE
The Boston Globe not working

### ISSUE THREAD

**Issue by birgerjrj** [iamadamdev/bypass-paywalls-chrome#524]
Tried the recommended steps (turn off uBlock, uncheck general bypass). I get a flash of text which immediately disappears, leaving only whatever image accompanies the article.

For instance:
https://www.bostonglobe.com/sports/redsox/2020/02/20/brock-holt-never-expected-wear-any-other-uniform-but-red-sox-uniform/3hJnHyMOyUAU2VQJBlOZoI/story.html

Thanks!

**Comment by iamadamdev** [comment]
Fixed

**Comment by birgerjrj** [comment]
Thanks for looking into it. But I still get the same behaviour - tried toggling general bypass, toggling uBlock. Not even getting a flash of text now, just the photo from the article.

**Comment by spoetnik412** [comment]
Use https://github.com/magnolia1234/bypass-paywalls-chrome-clean
